apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Define o namespace para todos os recursos
namespace: selecoes-stg

resources:
- ../../base
- namespace.yaml

patches:
- path: patch-deployment.yaml
- path: patch-ingress.yaml
- path: patch-hpa.yaml

# MERGE com valores específicos de STAGING
configMapGenerator:
- behavior: merge
  literals:
  - LOG_LEVEL="info"
  - MESSAGE="Serviço Seleções Staging"
  name: selecoes-config
  options:
    disableNameSuffixHash: true

images:
- name: dti-registro.unilab.edu.br/unilab/selecoes
  newTag: stg-28547694
