apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selecoes-prd
resources:
- ../../base
- namespace.yaml
patches:
- path: patch-deployment.yaml
- path: patch-ingress.yaml
- path: patch-hpa.yaml
configMapGenerator:
- behavior: merge
  literals:
  - LOG_LEVEL="error"
  - MESSAGE="Serviço Seleções Production"
  name: selecoes-config
  options:
    disableNameSuffixHash: true
images:
- name: harbor.unilab.edu.br/unilab/selecoes
  newTag: v7.0.2
