apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selecoes
  annotations:
    kubernetes.io/ingress.class: "haproxy"
    haproxy.org/check: "true"
    haproxy.org/forwarded-for: "true"
    haproxy.org/load-balance: "roundrobin"
    haproxy.org/proxy-body-size: "0"
    haproxy.org/ssl-redirect: "true"
    haproxy.org/websocket: "true"
spec:
  rules:
  - host: selecoes-staging.unilab.edu.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: selecoes
            port:
              number: 80