apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: selecoes

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealed-secret-regcred.yaml
  - hpa.yaml

configMapGenerator:
  - name: selecoes-config
    options:
      disableNameSuffixHash: true
    literals:
      - LOG_LEVEL="info"