---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgBJQYCJ2Kn9LTkcYqgEpfS1RQ6X4VWvDd0i7wzFRWjkxWb2/GMD7O9dPGv45EXNYuolNjCblfyD4K7NaF1QoazalBLkXQNwPt7PCqOyhRKP2C/68UxlT9rzb3Pw0g2+m9uG9od79RLbdwcyZgm4zPhI5sY3VyweFksNu9ktQcPdYndvT01w8PB/ZAWHsnEitkwmHBv05sl4bP4BRzQc4Py6dyIUA/P5v7ymjCCENG8Wpvs3q10KqhbKMqeosSDb/JV0EObGoXj6gjhsRTeXYctabW5k8hvPjI0uZA5+scma75AIAGu+7gdom09BI7TWazBiXAFyS3SdAT1eOu9j7vkeROrgUex3Dam7BowvnQ1KvafBul2/060/apR1MCn0Ffnejp/F0vRfqIjwbk4iHGz4xt/axy6aEtnQBIxZtyN0MaRU1po7X6EGG0vs989hr7smwEvTGxorWZaaCBQHwQv0At2iQ+YMnwNC4N9YdOMj3sE1TK3x3mLjD3FVWgmm9Zv0DgKQgnNzbzxGhvf0vJcBmPiEuYAJ0mSNYZRqVpZf2e6+i+5mTFzFKP7V1IZqX7hFnqOj0Qp8CRrqNl9XYnCICD/r4FPSZLp5Kn/okM9RON544lM6TbD4xoZ0Ng12p5lbGmYYmNQ4EO38L01Mu91HhMureQ9AKiWLpLXvbljy2CTK6HlysvmZxqTCHpyZ1CfTkG27l4FM41CH4KtYUiQgxVewbzwEyXt7T/8hyeUWpwE1lpeK7Fj2Rmfcr+TkWqmmHfhqR9SxsXZG4yF1ofYFj84dpHCBv8IVSGdGd46RGmFZkWbV5vM/f4Fmchv7846SPCTwUD8dMTiuszBe8ztYHznvEXFLpG47fnPHmGG3JqRudYu+tBvPgYZRUPBb8GUPy1u0yp7p0kHPfSBZa60tgeXJbH6vANrGc/7WJhpnnGp/3VyJjY9ThGEJCTjXH0uz5yNDc7dznD/zvymEtfgHRPT2EF3AcB4JOJo=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
