
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgCDeHZeFnqploJZGbcslMtMe3f/4DPJn4jZ6B+TyPjH5391MCdRMJxBgNDXMAc0oK6YRC0c+YeXSvV++PNrv3hW/e+2T/JWLurIYksQCy1pGR8OxCkjOK2Zi+gX8QZmYhcsG3IRXknKR8JId3MMPpVbeVg+gbZQbEjIRdBPYNgE5eVky5TKEzx6DmyiKrqO9zj5BWAiZXYUduf9sLSGBM6nLYhIQHr3Toy/z5navty0jw6zUgHY20l4FLI0/wy3i4U8aYrKtflZAwF1ClOxXi65TjyL41xx9uOCoJNLbrVtAITpyg+BsQs71UncUiJ4SWgXA1CrBXKTy6hYxpb0Hnr5UfblsFTvqczEKSzHRdXzrsdLdAeQu1iiWeC4iguFMkZGKjgPmh4RsfWiAKsE1K4gIOLt6k5tRVIUQw4++DHky+hdGTyLU0YCd7Wfm15A2iGx3GqNFaUpOm6oQR7IzV6xyRi3o0/3vmGmOLPRQgzhFQ8qV+HtUvb0ns2RPmRdSrnqxm7UU5H31y89IovDRo3iX41wtzxW31k/sfoueg9GqFllpF4n0ULMBX9C/A0BQTCJ6ydlVFap/HQI5wH0+1siaya8/LVaKtTbfRwlZG46XYTcgmPwfMo7HT/wRUlcVZuqx00D8BgxmDprWkWsvPl9jXsoOhtV5kAmheAsPAERU+E0g20wd1A4es6HqyCv8lNh7+vVOl52XLtdPw4p4YGaHzbLcZ1UihuieEd3AE/kn7Jz59Et+gUomPfHU/XLPWMLMGaDjs6vmZrFbSk84kthuFlYmRphX4InbuYY0/scrl8KulTE33lnDoz8/IFSlZPCwotde6AJgxiVgt7vM8f88Jzy0n2xTWOL/k2XnCveRu//VTw3an9YItVnvajv6Eezbrt4cl0U3zDJLQs6GGkVr02KELCy0fb3WCjRdPzyZ/KDvS6VOffOgXwr7j5B+iLIWUQzosqc2iMmE+mXqnaq
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: regcred
    type: kubernetes.io/dockerconfigjson
