---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgAnUfHsOTXViLS/KMsAcOvhJB+B9z08JKcUPzveYhfhAAGZQvdh+N24XdZLWkE0G7E7CgIzjT+0aHI9PI4RfoGfWrlEy0F0LMrYzFouIVLn6uONGYaMI+oEqOn5L7cjMFeUfs68ebra1YYxJuqM2C8It2mV5JzdcFvBQDmsqYGGH/s45n6oXXJyk4Di0gKeGbaevHoMSgIrCIRb/n/cNpDk+MflYc4sIgbFY8RQ8WvIGxi+18ZnZ1pPx3NzapwE+MXt+4tuqS//sjt6qQEx/91pngXwsGlOQS9CMXRCm2kFgAXqtiGPgzlhTTb/nG56d0T/ir4YyjrrAXv+/ys6fD5oGG3ZN/R83co4L2FK8jPgqbYG1U2vAXCOpm/2/72KkoYXUQq6HbIYnmStZ5svu3do2Vk4T52oiIELthRNJoyFqMFnRjYjtfvkYtVtSQp59dxHmSZJRnY2hrlQl5Cxhnd3KKKqzGaUMij1AgbYuHJ/ofsnhMEafaTrYWIs8RfKI9ZdzTa4kUsOwOySz/BAENBg3pua8Xco1JAR+ZHbiRXz429o3xKYU6dzUPMLklG5QEE5IjzFsx1sWxwDQrlVNj3M7P18+vQs6B6IBNmCyQF2ax5Mb/RFabUaG2Gx57RbB23xbDSjiFDnNCKOBJx6EIk06Stl18BZx9G/Gw3zT+bwDmxNApyXhlaTjasENFPuPYofapx4/2HeSFbwsOAWOQhONA+uKWhehlfdOCXSXllk0B5mOprJitXYt5/qbEJmduuKQB2aLY5hzSHuRD9GFnvag+U/RipJ1UmnSK1aidQoTw/y1HFzw0py2CSQiQrPhSWPs5ZeJv+Lzkha7I2NZJywKUfOtqZtjmL7vT9tjgRNdu+qun8xI+f79VR5ti6Qe7/4rgsw62couwBKUhNxXX2QzuQaLy7L+qByC/YWrKxzygDS4n6OYkpANOgGOLWXlyoyeD5mlUPLf9j1Xaj3worigR9VwIWlRoh8XBTrgty7Xkg=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson
