apiVersion: v1
kind: Service
metadata:
  name: selecoes
  annotations:
    metallb.universe.tf/address-pool: int-pool
spec:
  selector:
    app: selecoes
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: selecoes
      protocol: TCP
      port: 80
      targetPort: 80